version: '3'


services:
  db:
    image: postgres:12.4-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=admin"
      - "POSTGRES_DB=mutify"
      - "MIGRATE_NEW_DB=0"

    volumes:
      - "./DevopsConfig/db:/docker-entrypoint-initdb.d"
      - "shared_data:/app/shared_data"
#      - "shared_data/stored_db:/var/lib/postgresql/data"
    networks:
      - mutify-network
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    restart: on-failure
#    ports:
#      - "80:8000"
    environment:
      - "ASPNETCORE_URLS=http://*:8000"
    volumes:
    - "shared_data:/app/shared_data"
    depends_on:
      - db
    networks:
      - mutify-network
  proxy:
    image: nginx
    depends_on:
      - api
    volumes:
      - "./DevopsConfig/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - mutify-network
    ports:
      - "80:80"
networks:
  mutify-network:

volumes:
  shared_data:
